### ISSUE TITLE
long file names

### ISSUE THREAD

**Issue by punyetta** [ADTPro/adtpro#107]
Just came across an issue when I was trying to write a po image with filename 45 character long.  Error was "no files found" and renaming file 10 characters shorter fixed it. I don't know what the maximum is but 35 seemed fine.

**Comment by david-schmidt** [comment]
It's just about 40 characters - there is some brain-dead screen-scaping that goes on that won't wrap around to the next line.

**Comment by david-schmidt** [comment]
Oh, hey, I just remembered... I fixed that. :-)  It'll be in the "next" release, which maybe is some impetus for me to get that out: https://github.com/ADTPro/adtpro/issues/53
