### ISSUE TITLE
Strange content during Serial Transfer (Win10 64 bit to Apple //c)

### ISSUE THREAD

**Issue by lealadri** [ADTPro/adtpro#118]
Hi folks, I have a Apple //c, and FT323R (FTDI original) USB/Serial cable. 
Did the connections between DIN5/232 Pinout, and went through the MY_JAVA_HOME to downgrade my Java version with a 64bit (yes, I'm running Windows 10).
So far, so good, I'm able to start Serial Port ADTPro Server, and activate Bootstrap, but I only get stranger characters during the transfer (which seems to indicate my tx/rx cables are properly connected). 
I tried multiple COM ports (1-3-6) and speeds from 115200/8/N/1, to 1200/7/S/1 (hardware control and none flow), and all I get is this:

[Video.zip](https://github.com/ADTPro/adtpro/files/5442367/Video.zip)

After stream is sent, ADTPro states "File sent in 15 seconds"
![image0(1)](https://user-images.githubusercontent.com/50211600/97246217-2f0f4400-17d3-11eb-8b2c-fe909292e96a.jpeg)

My ROM is V4.
Seems like parity RTS/CTS (tried looping back in PC and //c sides), since transmission is working and ADTPro Server recognizes the bootstrap request.... but any clues ?
Thanks in advance !

**Comment by david-schmidt** [comment]
Closing this as it's being chased on Facebook.  It's likely a mismatch of baud rates (never change the baud rates, it won't help, I promise) or a hardware port problem on one end or the other.
