### ISSUE TITLE
Fix bad link to buy floppy disks on web site

### ISSUE THREAD

**Issue by ryandesign** [ADTPro/adtpro#139]
On the page http://adtpro.sourceforge.net/misc.html it says:

> Buying Blank Disks: If you need new blank floppy disks, they can be purchased here.

"here" is a link that is 404 not found. The correct link to put there is:

https://retrofloppy.com/products/#BlankDisks

**Comment by david-schmidt** [comment]
Very clever of you to find a deep link in the old sourceforge site.  I've uploaded redirects for every page that will take you to the right place.
