### ISSUE TITLE
ADTPro 2.1.0 not launching on Apple IIgs

### ISSUE THREAD

**Issue by dcgibbons** [ADTPro/adtpro#143]
This is the first time I'm using ADTPro at all on this hardware. I'm using brand-new cables (Apple IIgs to RS232 null on one side, and another with RS232 to USB on the other) connected to my macOS systems (I've tried both an M1 mac mini and a x86 2018 MacBook  Pro).

I'm able to get the IIgs booted and receiving data no problem. But at the end of the transfer, execution does not start. This doesn't seem to matter if it's ProDos or the simple client.

I tried changing the Pacing setting all the way down to 1000 just to make sure that wasn't an issue - no change in behavior.

I've also removed all of the cards from the IIgs to makes sure it's completely stock.

User error or is something else amiss here?

![IMG_2798](https://user-images.githubusercontent.com/250931/141699617-f8a5f721-3a3f-4628-a5d7-7ad98e3bba6b.jpeg)

**Comment by david-schmidt** [comment]
It looks like you're doing the manual bootstrap method, and it's not looking good.  Is there a reason why you're not doing Speediboot instead?  What does that look like?

**Comment by dcgibbons** [comment]
Speediboot was doing the same thing, actually.

All that said, today everything is working. The only thing I think I changed was switching Slot 4 from user card to the default in the IIgs' control panel. I will play with this more and see if I can recreate again with some consistency and re-open if needed!
