### ISSUE TITLE
100% CPU after running for some time

### ISSUE THREAD

**Issue by hackerb9** [ADTPro/adtpro#168]
Is it a known issue that ADTPro server ever uses up 100% of one CPU core? I had left the server running unattended after doing some transfers and when I came back the next day `top` showed that java was using up 100% CPU. I restarted the program, and the problem has not  reappeared, yet. 

Possibly relevant: I have "Activate Trace" turned on. I am using version ADTPro 2.1.0 with openjdk 18.0.2-ea 2022-07-19.

**Comment by david-schmidt** [comment]
Not a currently known problem, no.  I would definitely see if it reproduces without tracing on.

**Comment by hackerb9** [comment]
I've been running it for days and I can't reproduce the problem at all now, so I'll close this. Maybe the server had gotten into a funny state after the client crashed when trying to receive a NIB.
