### ISSUE TITLE
Feature Request: send test data for audio volume adjust

### ISSUE THREAD

**Issue by JPT77** [ADTPro/adtpro#169]
hi, 

it's a pain in the *** to find out the correct volume. you've got 4 possibilty what's wrong: sending, receiving, up or down... 
guessing correctly almost impossible.

could you please add a test mode to both clients were either of them continuously sends test data and the other end shows the signal quality.

thank you very much. 

ps. I almost got it, but somehow lost connection again. no idea why. 
I am using bootstrap mode to adjust the volume from pc to apple. but I keep getting monitor errors after the transfer is finished. so it's almost there.

**Comment by david-schmidt** [comment]
Your wish is my command:
https://adtpro.com/connectionsaudio.html#Testing

**Comment by JPT77** [comment]
Oh, sorry. didn't see it. 
thanks. wrong input o.O

I now got a connection, but it's bad.
whenever I request a directory listing I get parts of the filenames plus a lot of garbage. 
already tried adjusting the volume from 40 to 150%. the only change is that it eventually doesn't receive anything at all.
I got a high quality creative sound blaster USB sound card.

**Comment by david-schmidt** [comment]
I will say that you'll never be happy with an audio connection.  Find a way to move towards a serial or TCP/IP connection and you will be much happier.
