### ISSUE TITLE
Apple II/II+ using SSC II only can do 19200, please add this to your guide

### ISSUE THREAD

**Issue by JPT77** [ADTPro/adtpro#171]
Hi, 

I had as much trouble with serial connection as I had with audio connection. 
Could you please add some more specifics for old machines like the apple II and II+?

I am quite sure they are only capable of 19200 not 115200.

and please add more info about the Terminal/Modem Jumper as both my SSC II had a handmade jumper without the arrow.

I believe the wiring is as this

.-. .-. . . . . 
        ||||
.-. .-. . . . .

but no idea if this is Terminal or Modem config.

thank you very much.

**Comment by david-schmidt** [comment]
Machines all the way back to the non-plus Apple II run at 115200 just fine.  That's part of the hardware suite I test with.  As for the terminal jumper - sorry to say, I don't know how it's wired.  If you try and find out, let me know!
