### ISSUE TITLE
Apple /// issues

### ISSUE THREAD

**Issue by PontusO** [ADTPro/adtpro#176]
The ADTPro client download seems to be working OK. I get to the screen saying "ADTpro    /// OK  ///     T" but the system seems to be hanging at that point. There is a click from the speaker as if the system is trying to reset but it gets stuck for some reason.
Any pointer on where to start digging ?

**Comment by david-schmidt** [comment]
That means the download completed, and the next step is to start SOS itself.  The message we send out is exactly `"   ///   OK   ///   "` so the trailing `T` looks like something that was a side-effect of SOS... which seems to not be coming up on your system.  My first guess is to look at the hardware and make sure the memory is all happy.  If you have an Apple II that can be used to generate disks with ADTPro, you might want to grab a copy of dealer diagnostics (https://apple3.org/Software/system/Apple3Diagnostics.dsk) to see if it can find anything wrong with your machine.

**Comment by PontusO** [comment]
Thank you. I replaced all RAM chips with new old stock ones and now everything works.

**Comment by david-schmidt** [comment]
That's great news - congratulations, and enjoy!
