### ISSUE TITLE
EsDOS transfers via audio but does not work on ][+

### ISSUE THREAD

**Issue by markaudacity** [ADTPro/adtpro#183]
Got my volume levels set so I can reliably transfer both parts of EsDOS, but when I enter 9D84G per the instructions after transferring part 2, I get what looks like a very garbled splash screen (SFSDSC-C, alternating reverse video, dash is blinking) and entering any text triggers a register dump in the monitor.

Once I was able to get a ] prompt, but as soon as I typed INIT it once again crashed.

**Comment by markaudacity** [comment]
64k, 48k base and a 16k Microsoft language card. 
I can’t guarantee it’s all good, as far as I know the Plus doesn’t have the built-in self test of the e; is there a way to check without being able to boot?

Additional diagnostic information: ProDOS will transfer and display the boot screen, but immediately drops into the monitor prompt.

**Comment by david-schmidt** [comment]
You can do a quick type-in check without disk access with this:
http://erikarn.github.io/apple-ii/memory_test.html

But it sounds to me that you've got some bad memory on your hands.

**Comment by markaudacity** [comment]
Closing the loop: it was in fact bad RAM

**Comment by david-schmidt** [comment]
Fantastic, thanks for that!  Enjoy your newly minted, fully working Apple II+.
