### ISSUE TITLE
USB Serial not recognized Mac M1 Sequoia 15.1

### ISSUE THREAD

**Issue by Gliou** [ADTPro/adtpro#195]
Hi
On MacMini M1 with Sequoia 15.1
Not USB-Serial Controller in the list
ADTPro with jssc-2.9.6.jar and I try with ADTPro-v.r.m same issue

![Capture d’écran 2024-11-03 à 16 16 30@0 5x](https://github.com/user-attachments/assets/0c3351d7-2e89-479c-92f5-4d91eba2bc8f)

**Comment by david-schmidt** [comment]
I would not recommend a Prolific-based USB controller - they have always been problematic.  They haven't updated their driver in years... but you may need to install that in order for it to show up in the list.
