### ISSUE TITLE
"There are no serial ports, or the serial library RXTX is not installed or visible"

### ISSUE THREAD

**Issue by fhorlaville** [ADTPro/adtpro#197]
Hi, the error message in the title appears when trying to use a USB/Serial adapter on Mac OS Sequoia 15.1.1. It then says "Please see http///adtpro.com/install.html for details" but this error message does not seem to be described there.

The serial port is seen by the Arduino IDE and the Terminal as /dev/tty.usbserial-2110

Many thanks,

F.

**Comment by david-schmidt** [comment]
I'm guessing you're on a laptop with Apple Silicon chip in it.  You'll need to download the Apple silicon testcase release instead:
https://github.com/ADTPro/adtpro/releases/tag/applesilicon
