### ISSUE TITLE
how to move a disk image i download 

### ISSUE THREAD

**Issue by scooter87** [ADTPro/adtpro#22]
I'm using a mac book pro using os sierra 10.12.6 i got adtpro and it works but when i go to put my disk image into the disk folder in adtpro it will not let me move it into the folder and i don't know what I'm doing wrong and i haven't been able to find any info for this

**Comment by david-schmidt** [comment]
This sounds like a question about moving files in the MacOS finder rather than something about ADTPro - am I reading that right?  Can you be any more specific with what you're seeing?

**Comment by scooter87** [comment]
yes it will not let me movie files to the disk folder i getting my files from apple2online

**Comment by david-schmidt** [comment]
Ok, but what is preventing you from dragging them in?  Is it a folder permission problem?

**Comment by scooter87** [comment]
im not for sure how to fix that problem

**Comment by david-schmidt** [comment]
Right, but when you opened the .dmg, did you copy the ADTPro folder to the Applications folder as instructed, or are you running it right from the .dmg?

**Comment by scooter87** [comment]
wow thank you sorry about this its working fine now
