### ISSUE TITLE
Error / scam on RetroFloppy Products page

### ISSUE THREAD

**Issue by Vorocity** [ADTPro/adtpro#39]
The "Click here" on this line in the Apple II Audio Bootstrapping page, links to this page: http://retrofloppy.com/products/#ADTPRO

"If you'd rather have a pre-built ADTPro floppy disk arrive at your door than create one yourself, **click here**."

If you purchase the disk for $9.95, it attempts to charge $9,995 to your paypal.

**Comment by david-schmidt** [comment]
You might not have noticed on the top of the page - if you're from outside the US, you can't just order straight from the page.  Since PayPal won't let vendors restrict countries that are shipped to, the exorbitant shipping charge to non-US destinations is there to alert you something is amiss.

**Comment by Vorocity** [comment]
Good to know. I've never come across that before. I was one step to clicking purchase before i noticed it. Charging me $10k would have been a nasty surprise.

**Comment by david-schmidt** [comment]
Don't worry - it wouldn't have been a surprise.  Nothing happens in PayPal without your consent - and the ridiculous charge did what it was intended to do, call attention to the fact that we don't ship internationally without you getting in touch with us first.
