### ISSUE TITLE
Investigate ProDOS 2.4.2?

### ISSUE THREAD

**Issue by inindev** [ADTPro/adtpro#40]
I noticed adtpro uses ProDOS 2.4.1, does it make sense to update the base image to 2.4.2 for the next release?

https://github.com/ProDOS-8/Info/releases

**Comment by david-schmidt** [comment]
Indeed it does.

**Comment by david-schmidt** [comment]
I know and trust Oliver Schmidt, but I'd want to learn more about how John Brooks is moving his code from his usual distribution method (Call-A.P.P.L.E.) over to github:
http://www.callapple.org/vintage-apple-computers/apple-ii/announcing-prodos-2-4-2-for-all-apple-ii-computers/

**Comment by inindev** [comment]
It looks like it is located there too:
http://www.callapple.org/soft/ap2/system/ProDOS_2_4_2.dsk

**Comment by david-schmidt** [comment]
Integrated with this commit:
https://github.com/ADTPro/adtpro/commit/0c8ba17f0daec09496ec81d618bd85d8a62ae97a
