### ISSUE TITLE
Serial port issue revisited

### ISSUE THREAD

**Issue by clh333** [ADTPro/adtpro#61]
Trying to use ADTPro to communicate between a Win7x86_64 machine and an Apple IIgs for which I have no software.  I have ADTPro version 2.0.3 downloaded and unzipped; I have Java RE 1.8.0_191 which is supposed to be 64-bit, and Java HotSpot client VM 21.195-b12, mixed mode.

The server starts when adtpro.bat is invoked.  Although the IIgs is at a prompt and connected to the Wintel machine, serial to serial and with a null-modem between, and although Device Manager and a term program both recognize the serial port as COM4, the ADT server says there is either no serial port or the RXTX library is not installed or not findable.

Just to eliminate that possibility I copied everything from the libs folder into the folder where adtpro.bat resides and restarted the server.  No success.  The serial port is on a PCI-e card, SUNIX is the mfr, their driver 8.3.0.0 is in use.

Not sure how to proceed.

**Comment by david-schmidt** [comment]
`RXTX library is not installed` is a dead giveaway.  One or the other of [Windows|Java] is not 64-bit.  Output from my `java -version`:
`Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)`

**Comment by clh333** [comment]
Thank you for your reply:  Your diagnosis was correct; I was running a 32-bit version of Java.

When I began the process of installing ADTPro I discovered that it wanted a JRE.  I had removed Java some time ago due to security concerns, so I fired up Firefox and searched for the Oracle site.  The first thing I discovered is that Firefox wants nothing to do with Java any more.  Undeterred I fired up IE 11, which obligingly downloaded Java.

What I did not realize is that my IE is also a 32-bit app and that by default it will go to and download the 32-bit version of Java.  I uninstalled the 32-bit and found a manual download of the 64 bit version, then copied the libs files to my Java Home as instructed in install.txt:

NOTE: You MUST match your architecture.  You can't install the i386
version on a 64-bit version of the JDK and vice-versa.

For a JDK installation:

Copy RXTXcomm.jar ---> <JAVA_HOME>\jre\lib\ext
Copy rxtxSerial.dll ---> <JAVA_HOME>\jre\bin
Copy rxtxParallel.dll ---> <JAVA_HOME>\jre\bin

Restarting ADTPro I was able to communicate with the IIgs and transfer files to it.  The ADTPro client ran on the Apple.   Unfortunately I was unable to save anything but the process is debugged and eventually the proper drive will arrive to allow saving files.

Thanks again for your help!
-CH-

**Comment by clh333** [comment]
See attached.  Thanks again for your help.

 

-CH-
