### ISSUE TITLE
Macintosh plus serial port

### ISSUE THREAD

**Issue by Tommy51389** [ADTPro/adtpro#67]
Hello again!

I saw your previous comment, and I was wondering what cable I would need to connect from my Macintosh plus to my laptop?

I was thinking the DIN 8 serial modem port? I’m not entirely sure though. I assume that the receiving end would plug into the db25/parallel/printer port on the laptop side correct?

Thanks,

**Comment by david-schmidt** [comment]
What software are you planning to run across the serial wire?  There's not an application of ADTPro between a Mac Plus and a PC, so I'm not sure how this applies.

**Comment by david-schmidt** [comment]
It sounds like maybe you're wanting the Mac to be the client (as if it were an Apple II) and then feed it disk images via serial from the PC?  That's not possible with the current software.

**Comment by Tommy51389** [comment]
Yes I was referring to the Mac as the client and feeding disk images via serial from the pc. 

I understand now, thank you for you help!
