### ISSUE TITLE
ADTPro Under GS/OS

### ISSUE THREAD

**Issue by RealActorRob** [ADTPro/adtpro#73]
Yeah, it's a leap but it would be nice if it worked under GS/OS. Or am I doing something wrong? 

Executing it there gives me timeout errors.

Works great via bare metal or booted ADT floppy.

**Comment by david-schmidt** [comment]
Nope, GS/OS steals interrupts and time.  ADTPro talks to the bare metal.  The two don't/won't ever get along.
