### ISSUE TITLE
2.0.3. not working with Mac OSX 10.11.6

### ISSUE THREAD

**Issue by stratoculumus** [ADTPro/adtpro#94]
I have a fully working ADTPro 2.0.2 (USB-serial and audio) with an Apple II+ and a Mac running OSX 10.11.6 (El Capitan), but for some reason I can't get ADTPro 2.0.3. to work on the same computer. 
Nothing happens when I double-click the app on my Mac. I also tried opening it in the OSX Terminal (command line) by right-clicking on the ADTPro 2.0.3 app, selecting "Show package contents",  dragging the exec file into the terminal window and pressing return, like this:

$ **/Applications/ADTPro-2.0.3/ADTPro-2.0.3.app/Contents/MacOS/ADTPro-2.0.3**

and I get this error message:

Exception in thread "main" java.lang.UnsupportedClassVersionError: org/adtpro/ADTPro : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

I'm no programmer, but I'm guessing the problem has something to do with Java? 
I've checked my currently installed Java version like this, in the OSX Terminal:

$ **java -version
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)**

"Software update" on my Mac tells me that I've already installed all available updates from Apple. Is the problem related to something else, or do I have to "manually" install a new version of Java -and if so, where can I download it from?

**UPDATE:** I tried to update Java to see if that changed anything but I must have done something wrong....
Apparently there are numerous versions of Java, some needing to register before downloading, others not. I chose the latter and went to [https://www.java.com/en/download/mac_download.jsp](https://www.java.com/en/download/mac_download.jsp) which downloaded a file named **jre-8u241-macosx-x64.dmg**.
I ran the installer, and indeed a System preference named "Java" has now been installed, saying I have version 8, but the "java -version" command in the Terminal window still says I have 1.6 as before (which of course doesn't make sense as I just upgraded!).
... alas, ADTPro 2.0.3. still won't work.

So I did some further research and read in another posting with a similar problem in this forum to unistall version 1.6. I found out how to do that [on this page](https://explainjava.com/uninstall-java-macos/). Here's what the Terminal looks like when I did that:

**$ java -version
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)
$ 
$ ls /Library/Java/JavaVirtualMachines/
1.6.0.jdk
$ sudo rm -fr /Library/Java/JavaVirtualMachines/1.6.0.jdk/
Password:
$ 
$ java -version
No Java runtime present, requesting install.
$** 

I then rebooted just to be sure, and an alert popped up on my Finder desktop saying that Java was missing, needed for some of my Mac software, and that I should install "the legacy Jave SE 6 runtime" by clicking on a link in that alert. I assume this is the same 1.6 that I previously had before manually removing it in the Terminal using the above link. What a confusing mess!
And again, ADTPro 2.0.3 won't work -in addition to OSX complaining that Java is missing (and I can no longer run some of my OSX apps such as Photoshop).
Is there a (hopefully not too complex) solution for all of this?

Like I said, ADTPro 2.0.2. works fine for me, but I understand 2.0.3. has some new and useful features and improvements which I'd like to try out.

**UPDATE 2:**
Sorry about the post becoming so long, but I just tried something else, which I think worked....
Seeing that the above attempts didn't work I came across a link the [Oracle Java SE Development Kit 13 Downloads page](https://www.oracle.com/java/technologies/javase-jdk13-downloads.html) where I downloaded and installed a file named **jdk-13.0.2_osx-x64_bin.dmg**.
Now the version number has changed in the OSX Terminal:

**$ java -version
java version "13.0.2" 2020-01-14
Java(TM) SE Runtime Environment (build 13.0.2+8)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)
$** 

And best of all, ADTPro 2.0.3 now works! I haven't actually tried it with my Apple II+ yet, but I assume it'll work as the OSX app shows up in the same way as 2.0.2.

The strange thing is that the Java System preference still says I have version 8 (or 1.8), and I still can't run Photoshop as OSX complains about not having legacy Java SE6 runtime installed. Are there actually several different Java versions running on my Mac now? Is there a solution to all this, so I can run ADTPro _and_ my other apps (Photoshop etc.) relying on Java SE6, or do I have to choose one or the other? 
It's all pretty confusing and frustrating.

**Comment by david-schmidt** [comment]
So it looks like you're on the right track.  You're in Java purgatory now because you've got more than one level installed - and ADTPro sees the right one (you can point it explicitly at the one you want to use), but Photoshop doesn't know that you have the newer one installed since the "system" JVM is still at that 1.6 level.

**Comment by stratoculumus** [comment]
Are you saying that with Java, you can install different versions/types alongside each other, instead of having the latest version replace everything else?
Seeing that "jre-8u241" did no good on my machine I finally found instructions on how to remove it.
I believe I now have two types of Java on my machine: the "legacy" 1.6 (downloaded from one of Apple's sites) which allows Photoshop to run, and Oracle "jdk-13.0.2" which allows ADTPro 2.0.3. to run. Is this the correct way to do it?

I'm probably not the only ADTPro user who finds this confusing and isn't into programming and such: can you consider adding some easy to understand information about all of this in a readme file for ADTPro? And if possible, a clear error message in the app itself (i.e. "Incompatible Java version -please install version xxx or higher") and maybe even a download link for what's needed as all the "SE", "JRE", "JDK" along with the choice between Oracle, Java.com and Apple's own Jave distributions can be quite confusing.

**Comment by david-schmidt** [comment]
Unfortunately, it's a fairly deep problem with open-ended possibilities and consequences.  And it's been made harder by Apple stopping support on your operating system some time ago; they've left you to manage Java yourself.  I appreciate that you found it a difficult problem to surmount, and I'm glad you got through it!

**Comment by stratoculumus** [comment]
Thanks!
Yes, Apple sometimes like to make things harder than necessary unfortunately. 
I see that there's some mention of Java versions in [the "installation" section](https://adtpro.com/install.html) of the ADTPro website, but could you add that on the Mac platform at least you can (if I've understood it correctly) install both the "legacy" Apple Java version download along with the Oracle one I downloaded, and with links to them?
That could save a lot of users some pain and frustration.
