### ISSUE TITLE
Not able to get ADT Pro to work in Linux, even after viewing http://adtpro.com/install.html

### ISSUE THREAD

**Issue by insectorx84** [ADTPro/adtpro#97]
Hi.  Thanks for the awesome software!  I can't wait to use it.  I'm trying to use a netbook, running Lubuntu 18.04 LTS, to be a dedicated ADT PRO server for my Apple IIgs (windows doesn't run very well on the netbook).
Here is the error I keep getting:
"There are no serial ports, or the serial library RXTX is not installed or visible. Please see http://adtpro.com/install.html for details"
Also, I there isn't any COM 1, COM 2, or COM 3 options available under the "ports" menu.  It's empty.  

So far, I've gone to some Linux support chat for help, because I thought it was Linux not recognizing my serial adapter. The people on that chat helped me confirm that the adapter was indeed being seen by linux.  We tried a number of other things including adding "dialout", all of which didn't work.  (although the "code" in terminal that they had me type in looked different than yours for some reason.  Is there multiple ways to do this sort of thing in terminal, or something?)

Edit: I have been to http://adtpro.com/install.html, but I'm not getting the same RXTX error that is listed there, even when I have selected "execute from terminal".  Also, I don't understand what it's trying to tell me to change in the adtpro.sh and adtpro.command files.  Thanks in advance for any help.

PS - even though I've been using Ubuntu, on and off, for the past 10 years or more, I haven't made it that far past understanding the GUI.  I can follow a step by step tutorial that's set in the terminal, and have many times, but the stuff that you have to type in seems like impossible to remember gibberish to me 90% of the time.   So, thanks for any help.  I appreciate it.
PSS - I'm not sure that I've ever done anything in Linux that wasn't a total pain, that required me to post in forums or google search for hours.   You can't even change the clock settings of Lubuntu without knowing some sort of special code that needs to be looked up (I can't imagine a reasonable purpose for that).

thanks again!

**Comment by david-schmidt** [comment]
There's a couple of things that are going to need to happen - first, we'll need to find out if the binary RXTX library will even run on your particular distro of Linux - and if so, which one it is, and then tune your startup script to use it.  That's mentioned specifically here under "UNIX Considerations": 
https://adtpro.com/install.html#Considerations
(though it doesn't discuss *how* to make that change on a new Linux distro (one that isn't natively supported by ADTPro)).

So the secret is going to be in `adtpro.sh`.  You'll see that it's making decisions based on these three commands:
```
uname
uname -p
uname -m
```
So if you could supply the output from those three commands when you run them from a terminal window, that will shed light on what decisions your script is making.

**Comment by insectorx84** [comment]
Thanks the the reply, I really appreciate it!
uname = Linux
uname -p = x86_64
uname -m = x86_64

after opening adtpro.sh I quickly saw where to enter these.  I also saw that there was a spot to enter the location of the ADT PRO folder (mine's on the desktop).   I entered those 3 values in (uname, uname -p, and the path to ADT PRO's folder).  
At first, ADT PRO wouldn't open at all after I made those changes, but I had initially misunderstood how to enter the values. 

I had changed:
OS='uname'
OS-ARCH='uname -p'

To:
OS='Linux'
OS_ARCH='x86_64'

But when I removed the apostrophes the program would open normally again.

Now when I'm opening the program, I'm getting this error in the terminal : "RXTX Warning:  Remove stale lock file. /var/lock/LCK..ttyUSB0".   Also The Bootstrapping Menu is grayed out.  When I click the serial button nothing happens.

Thanks again for the help.
-PVH

**Comment by david-schmidt** [comment]
Well, you definitely didn't want to do any of that.  Please revert your `adtpro.sh` shell script back to the way it was originally.  There's a difference between single quotes (') and backtics (`), and they have significance in how they perform in shell scripts.

Once you've done that, what is the output from the script if you run it from the command line?  (i.e. `./adtpro.sh`?

**Comment by insectorx84** [comment]
Ok.  My bad.  I replaced the adtpro.sh file with a new one from the tar.gz

I navigated to the ADT PRO folder and opened adtpro.sh using ./adtpro.sh

When I open it, it gives me the same error in the terminal as last time:  
RXTX Warning:  Removing stale lock file. /var/lock/LCK..ttyUSB0

(Im down to reinstall a different distribution of Linux if it will work better with ADT PRO.  It just would have to be lightweight for this netbook.  I'm going to make this a dedicated ADT PRO machine, so I don't mind.  I just chose Lubuntu, because I thought it's supposed to be a less resource hungry version of Ubuntu)

**Comment by david-schmidt** [comment]
Ok, what if you run it as sudo?  `sudo ./ADTPro.sh`?

**Comment by insectorx84** [comment]
running it as sudo gets it to open without that error.  
It displays this in the terminal:
ADTPro Server version 2.0.3

Then it brought up the GUI part of the program

The program is working & actively transfering data to the IIgs!  :) 
But is there an easier way to open this program each time?

**Comment by david-schmidt** [comment]
Sure, you can correctly configure your user to have appropriate permissions on your box. :-)

It's possible you actually have residual lock file that need to be removed; you can check out this blog for a similar experience:
https://smdaudhilbe.wordpress.com/2013/05/01/how-to-solve-serial-port-problem-removing-stale-lock-varlocklck-ttyusb0/

Also, adding yourself to the `uucp` group should help:
https://github.com/c-flynn/Nunchuckoo/issues/2

**Comment by david-schmidt** [comment]
Closing as any additional details are going to be specific to OP's Linux installation.
